version: '3.8'

services:
  # PostgreSQL Database for Users
  postgres:
    image: postgres:15
    container_name: uala-postgres
    environment:
      POSTGRES_DB: UalaChallenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yoursecurepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uala-network

  # MongoDB Database for Tweets
  mongodb:
    image: mongo:7
    container_name: uala-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - uala-network

  # Redis Cache for Timeline Optimization
  redis:
    image: redis:7-alpine
    container_name: uala-redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - uala-network
    restart: unless-stopped

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: uala-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - uala-network

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: uala-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - uala-network

  # API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uala-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres;Database=UalaChallenge;Username=postgres;Password=yoursecurepassword
      - ConnectionStrings__MongoConnection=mongodb://root:rootpassword@mongodb:27017
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__Kafka=kafka:9092
      - MongoDbName=UalaChallenge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis
      - kafka
    networks:
      - uala-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  uala-network:
    driver: bridge
